//! # pebbles-shell
//!
//! The desktop shell: the only crate that touches the GPU and the OS window. It
//! wires [winit] windowing to a [wgpu] surface and the Vello GPU
//! renderer, and drives the [`Ui`](pebbles_core::Ui) engine each frame.
//!
//! The public surface is deliberately tiny — build a widget tree and hand it to
//! [`App`]:
//!
//! ```ignore
//! use pebbles_shell::App;
//! App::new(my_root()).title("Hello").size(480, 320).run()?;
//! ```
//!
//! The render backend is chosen by a feature that forwards to `pebbles-render`
//! (`vello` default, `vello-hybrid` opt-in). The GPU host for each lives in `gpu`;
//! the runner's frame loop is backend-agnostic.

// AccessKit has no web adapter yet, so wasm gets a no-op bridge with the same
// public surface (so the runner needs no per-call-site cfg). See
// documentations/web-support.md §4.4.
#[cfg(not(target_family = "wasm"))]
mod a11y;
#[cfg(target_family = "wasm")]
#[path = "a11y_stub.rs"]
mod a11y;
mod app;
// The GPU host seam (wgpu context/surface/renderer) — one impl per render backend.
mod gpu;
mod hotkeys;
#[cfg(all(feature = "native-menus", any(target_os = "macos", target_os = "windows")))]
mod native_menu;
// Opt-in hidden-input IME bridge (App::web_ime) — winit can't do IME on a canvas.
#[cfg(target_family = "wasm")]
mod web_ime;

pub use app::App;
pub use hotkeys::{HotkeyId, register_global_hotkey, unregister_global_hotkey};

// Android entry-point plumbing. On Android the OS calls `android_main(app:
// AndroidApp)` (generated by `#[pebbles::main]`), which stashes the `AndroidApp`
// here so `App::run` can build the winit event loop with `.with_android_app(..)`.
#[cfg(target_os = "android")]
pub use winit::platform::android::activity::AndroidApp;

#[cfg(target_os = "android")]
pub(crate) mod android_entry {
    use std::sync::OnceLock;

    use super::AndroidApp;

    static ANDROID_APP: OnceLock<AndroidApp> = OnceLock::new();

    /// Called by the `#[pebbles::main]`-generated `android_main`. Not for app use.
    #[doc(hidden)]
    pub fn __set_android_app(app: AndroidApp) {
        let _ = ANDROID_APP.set(app);
    }

    /// The stashed `AndroidApp`; panics if `android_main` never ran (i.e. the app
    /// forgot `#[pebbles::main]`).
    pub(crate) fn android_app() -> AndroidApp {
        ANDROID_APP.get().expect("android_main did not run — add #[pebbles::main] to your main fn").clone()
    }
}

#[cfg(target_os = "android")]
pub use android_entry::__set_android_app;
